language: node_js

node_js:
 - stable
 - lts/*

cache:
  directories:
    - node_modules

stages:
  - test
  - release

jobs:
  include:
    - stage: test
      before_script: npm run build
      script: npm test
      after_success: npm run coverage:ci
    - stage: release
      script: npm run build
      deploy:
        provider: script
        skip_cleanup: true
        script: npx semantic-release
      branches:
        only:
          - master
        except:
          - /^v\d+\.\d+\.\d+$/
